sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "ciprian droc" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: ciprian.drocl@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 A blogsite to showcare scripts and apps I'm working on
author: Ciprian Droc
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: 
  card: summary #keep this to generate a twitter share card